```{r setuphiermodel4, include=FALSE, cache=F}
rm(list = ls()) ; invisible(gc()) ; set.seed(42)
library(knitr)
library(kableExtra)
if(knitr:::is_html_output()) options(knitr.table.format = "html") 
if(knitr:::is_latex_output()) options(knitr.table.format = "latex") 
library(tidyverse)
library(ggfortify)
library(rstan)
library(loo)
library(bayesplot)
library(brms)
theme_set(bayesplot::theme_default())
options(mc.cores = 4)
rstan_options(auto_write = TRUE)
opts_chunk$set(
  echo = F, message = F, warning = F, fig.height = 6, fig.width = 8,
  cache = T, cache.lazy = F)
```

# Multivariate model

## `brms`

```{r mdatamulti}
data <- read_tsv("data/mangrove_data.txt") %>% 
  dplyr::rename(plot = `Placettes`,
                id = `ID`,
                height = `Hauteur(m)`,
                d1 = `Diametre1(mm)`,
                d2 = `Diametre2(mm)`,
                diameter = `Moyennediam(mm)`,
                branches = `Branches(N)`,
                fruits = `Fruits(N)`,
                flowers = `Fleurs(N)`,
                pflower= `Presencefleurs(1/0)`,
                nci1 = `Competition_1(cm)`,
                nci2 = `Competition_2(cm)`,
                nci3 = `Competition_3(cm)`,
                nci = `Moyennecompetition(cm)`,
                density = `Densite(trees/m2)`,
                date = `Date`,
                time = `Heure`,
                soil = `Typesol`,
                openness = `Ouverture`,
                age = `Agemax(months)`,
                shore = `Distance(fromShore)`) %>% 
  mutate(time = as.numeric(gsub("h", "", time))) %>% 
  dplyr::select(
    id,
    height, diameter,
    branches, fruits, flowers,
    pflower,
    nci, density, shore,
    soil, openness,
    plot
  ) %>% 
  mutate(plotNum = as.numeric(as.factor(plot))) %>% 
  mutate_at(c("nci", "density", "shore"),
            scale) %>% 
  mutate_at(c("nci", "density", "shore"),
            as.vector)
```

```{r fitMulti, eval=FALSE, echo=TRUE}
bf_height <- bf(log(height) ~ nci + density + shore + (1|p|plot), family = "gaussian")
bf_diameter <- bf(log(diameter) ~ nci + density + shore + (1|p|plot), family = "gaussian")
bf_branches <- bf(branches ~ nci + density + shore + (1|p|plot), family = "poisson")
bf_fruits <- bf(fruits ~ nci + density + shore + (1|p|plot), family = "zero_inflated_poisson")
bf_flowers <- bf(flowers ~ nci + density + shore + (1|p|plot), family = "zero_inflated_poisson")

fit <- brm(bf_height + bf_diameter + bf_branches + bf_fruits + bf_flowers, data = data, chains = 2, cores = 2)

save(fit, file = "save/multi.Rdata")
```

```{r summaryMulti}
load("save/multi.Rdata")
summary(fit)
```

```{r ppcMulti}
pps <- lapply(c("logheight", "logdiameter", "branches", "fruits", "flowers"),
              function(x) pp_check(fit, resp = x))
cowplot::plot_grid(plotlist = pps)
```

```{r intMulti}
mcmc_intervals(fit, regex_pars = c("b_", "sd_", "cor", "sigma"))
```

## `stan`

Just try defining likelihood for each variable with the same latent variable !

$$y_{i,p} \sim \mathcal Plog (\alpha_p^l + \beta_1*nci_i + \beta_2*density_p + \beta_3*shore_p, \sigma)$$
$$\mu_p \sim \mathcal N (\alpha^l, \sigma_{plot})$$

$$l\in{1,2}|z_{i,p}\sim\mathcal B(p)$$
